module.exports = {
    FIRMA: "D3L1L4HR35t0_C4R0G4RC14",
    QUERY_VALIDATE_USER: 'SELECT USERNAME FROM USERS WHERE USERNAME = ? AND PASSWORD = ?',
    QUERY_SELECT_PRODUCTS: 'SELECT * FROM PRODUCTS',
    QUERY_CREATE_PRODUCT: 'INSERT INTO PRODUCTS (NAME, PRICE) VALUES (?, ?)',
    QUERY_UPDATE_PRODUCT: 'UPDATE PRODUCTS SET NAME = ?, PRICE = ? WHERE ID = ?',
    QUERY_DELETE_PRODUCT: 'DELETE FROM PRODUCTS WHERE ID = ?',
    QUERY_SELECT_USERS: 'SELECT * FROM USERS',
    QUERY_CREATE_USER: 'INSERT INTO USERS (USERNAME, FULLNAME, EMAIL, PHONE_NUMBER, ADDRESS, PASSWORD) VALUES (?, ?, ?, ?, ?, ?)',
    QUERY_UPDATE_USER: 'UPDATE USERS SET USERNAME = ?, FULLNAME = ?, EMAIL = ?, PHONE_NUMBER = ?, ADDRESS = ?, PASSWORD = ? WHERE ID = ?',
    QUERY_DELETE_USER: 'DELETE FROM USERS WHERE ID = ?'
};